package model.plugins

import kotlin.reflect.KFunction

/**
 * A runtime plugin is a function that can run process chain executables within
 * a certain runtime environment (see [model.metadata.Service.runtime]). The
 * function has the following signature:
 *
 *     suspend fun myRuntime(executable: model.processchain.Executable,
 *       outputLinesToCollect: Int, vertx: io.vertx.core.Vertx): String
 *
 * It takes an executable to run, the number of lines to collect from the
 * executable's output, and the Vert.x instance. It returns the output
 * generated by the executable (trimmed down to `outputLinesToCollect` lines).
 * If required, the function can be a suspend function.
 */
data class RuntimePlugin(
    override val name: String,
    override val scriptFile: String,

    /**
     * The name of the supported runtime environment
     */
    val supportedRuntime: String,

    /**
     * The compiled plugin
     */
    override val compiledFunction: KFunction<String> = throwPluginNeedsCompile()
) : Plugin
